###################################################################################################################
############################################### User defined params ###############################################
###################################################################################################################

### analysis_name: your analysis must have a unique name. This name will be both the name of your configuration file, and the name of the folder with all analysis
analysis_name: "huvec"


###################################################################################################################
###################################################################################################################
### Intersecting peaks params
union_peaks: 
    bed_ATAC: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_DNase/results/09_peak_calling/Dnase_L-tron.bed"
    bed_H3K4me1: "//project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K4me1/results/09_peak_calling/H3K4me1_L-tron.bed"
    bed_H3K4me3: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K4me3/results/09_peak_calling/H3K4me3_L-tron.bed"
    bed_H3K27ac: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K27ac/results/09_peak_calling/H3K27ac_L-tron.bed"
    bed_CTCF: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_CTCF/results/09_peak_calling/CTCF_L-tron.bed"
    peak_caller: "lanceotron"
    threshold: 0.5


###################################################################################################################
###################################################################################################################
### Remove blacklist params
remove_blacklist: 
    genome: "hg38"
    
 
###################################################################################################################
###################################################################################################################
### Multi coverages params
multicoverages: 
    bam_H3K4me1: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K4me1/results/07_merge/H3K4me1.bam"
    bam_H3K4me3: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K4me3/results/07_merge/H3K4me3.bam"
    bam_H3K27ac: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K27ac/results/07_merge/H3K27ac.bam"
    bam_CTCF: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_CTCF/results/07_merge/CTCF.bam"


###################################################################################################################
###################################################################################################################
### Compute matrix params
compute_matrix_bigwigs: 
    bigwig_H3K4me1: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K4me1/results/08_bam_coverages/H3K4me1.bw"
    bigwig_H3K4me3: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K4me3/results/08_bam_coverages/H3K4me3.bw"
    bigwig_H3K27ac: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_H3K27ac/results/08_bam_coverages/H3K27ac.bw"
    bigwig_CTCF: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_CTCF/results/08_bam_coverages/CTCF.bw"
compute_matrix_extra:
    referencePoint: "center"
    b: 2000
    a: 2000
    sortRegions: "keep"
    

###################################################################################################################
###################################################################################################################
# plot parameters
metaplot:
    title: "'Chromatin marks at open chromatin sites (+/- 2kb)'"
    upper_threshold: "auto" # or can be an integer value


# ###################################################################################################################
# ###################################################################################################################
# ### Plot compute matrix params
# plot_compute_matrix_extra:
#     samplesLabel: "H3K4me1 H3K4me3 H3K27Ac CTCF"
#     refPointLabel: "peak.center"
#     plotTitle: "'Chromatin marks at open chromatin sites (+/- 2kb)'"
#     sortRegions: "keep"


# ###################################################################################################################
# ###################################################################################################################
# ### Cluster regulatory elements params
# cluster_regulatory_elements:
#     range_definition: 60
#     maxThreshold: "auto"
#     plotTitle: "'Chromatin marks at open chromatin sites (+/- 2kb)'"


###################################################################################################################
###################################################################################################################
### Cluster regulatory elements params
compute_matrix_bigwigs_extra:
    bed_extra: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_POLR2A/results/09_peak_calling/POLR2A_L-tron.bed" #specify 'none' if no peak
    bigwig_extra: "/project/Wellcome_Discovery/sriva/data_and_metadata/huvec/2023-03-02_POLR2A/results/08_bam_coverages/POLR2A.bw" #specify 'none' if no bigwig
    tag_extra_data_input: "POLR2A"
    threshold: 0.5

###################################################################################################################
###################################################################################################################
### REgulamentary threshold
thresholdPeaks: 0.5