###################################################################################################################
############################################### User defined params ###############################################
###################################################################################################################

### analysis_name: your analysis must have a unique name. This name will be both the name of your configuration file, and the name of the folder with all analysis
analysis_name: "paper_CD14pos_monocyte"


###################################################################################################################
###################################################################################################################
### Intersecting peaks params
union_peaks: 
    ATAC: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/09_peak_calling/CD14pos_monocyte_Dnase_hg38_L-tron.bed"
    H3K4me1: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/09_peak_calling/CD14pos_monocyte_H3K4me1_hg38_L-tron.bed"
    H3K4me3: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/09_peak_calling/CD14pos_monocyte_H3K4me3_hg38_L-tron.bed"
    H3K27ac: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/09_peak_calling/CD14pos_monocyte_H3K27ac_hg38_L-tron.bed"  
    CTCF: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/09_peak_calling/CD14pos_monocyte_CTCF_hg38_L-tron.bed"
    peak_caller: "lanceotron"
    threshold: 0.5


###################################################################################################################
###################################################################################################################
### Remove blacklist params
remove_blacklist: 
    genome: "hg38"
    #bed: "blacklists/hg38.bed"
    
 
###################################################################################################################
###################################################################################################################
### Multi coverages params
multicoverages: 
    bamH3K4me1: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/07_merge/CD14pos_monocyte_H3K4me1_hg38.bam"
    bamH3K4me3: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/07_merge/CD14pos_monocyte_H3K4me3_hg38.bam"


###################################################################################################################
###################################################################################################################
### Compute matrix params
compute_matrix_bigwigs: 
    bigwig_H3K4me1: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/08_bam_coverages/CD14pos_monocyte_H3K4me1_hg38.bw"
    bigwig_H3K4me3: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/08_bam_coverages/CD14pos_monocyte_H3K4me3_hg38.bw"
    bigwig_H3K27ac: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/08_bam_coverages/CD14pos_monocyte_H3K27ac_hg38.bw"
    bigwig_CTCF: "/project/Wellcome_Discovery/sriva/Git/UpStreamPipeline/genetics/CATCH-UP/REgulamentary/results/08_bam_coverages/CD14pos_monocyte_CTCF_hg38.bw"
compute_matrix_extra:
    referencePoint: "center"
    b: 2000
    a: 2000
    sortRegions: "keep"
    maxThreshold: 1500


###################################################################################################################
###################################################################################################################
### Plot compute matrix params
plot_compute_matrix_extra:
    samplesLabel: "H3K4me1 H3K4me3 H3K27Ac CTCF"
    refPointLabel: "peak.center"
    plotTitle: "'Chromatin marks at open chromatin sites (+/- 2kb)'"
    sortRegions: "keep"


###################################################################################################################
###################################################################################################################
### Cluster regulatory elements params
cluster_regulatory_elements:
    range_definition: 60
    maxThreshold: "auto"
    plotTitle: "'Chromatin marks at open chromatin sites (+/- 2kb)'"


###################################################################################################################
###################################################################################################################
### Cluster regulatory elements params
compute_matrix_bigwigs_2:
    bigwig: "none" #specify 'none' if no bigwig
    peak: "none" #specify 'none' if no peak
    tag_extra_data_input: "POLR2A"
    threshold: 0.5

###################################################################################################################
###################################################################################################################
### REgulamentary threshold
thresholdPeaks: 0.5